var BankinfoList=[
	{bankcode:"ICBC",bankname:"工商银行",hotline:"95588",limitlist:[{type:"e支付",singleLimit:"1万",dayLimit:"1万"},{type:"网银支付",singleLimit:"500万",dayLimit:"无限额"}]},
	{bankcode:"ABC",bankname:"农业银行",hotline:"95599",limitlist:[{type:"K码支付",singleLimit:"1000",dayLimit:"1000"},{type:"K宝",singleLimit:"100万",dayLimit:"100万"}]},
	{bankcode:"BOC",bankname:"中国银行",hotline:"95566",limitlist:[{type:"中银快付",singleLimit:"1000",dayLimit:"1000"},{type:"动态口令+手机交易码",singleLimit:"5万",dayLimit:"50万"}]},
	{bankcode:"CCB",bankname:"建设银行",hotline:"95533",limitlist:[{type:"网银盾1代",singleLimit:"5万",dayLimit:"10万"},{type:"网银盾2代",singleLimit:"50万",dayLimit:"50万"}]},
	{bankcode:"CMB",bankname:"招商银行",hotline:"95555",limitlist:[{type:"卡号密码支付",singleLimit:"5000",dayLimit:"1万"},{type:"手机支付",singleLimit:"5000",dayLimit:"限额"},{type:"专业版",singleLimit:"500万",dayLimit:"1000万以上"}]},
	{bankcode:"BOCO",bankname:"交通银行",hotline:"95559",limitlist:[{type:"手机短信密码验证",singleLimit:"500",dayLimit:"5万"},{type:"USBKey证书认证",singleLimit:"500",dayLimit:"100万"}]},
	{bankcode:"PSBC",bankname:"邮政储蓄银行",hotline:"95580",limitlist:[{type:"手机短信客户",singleLimit:"1万",dayLimit:"1万"},{type:"电子令牌+短信客户",singleLimit:"20万",dayLimit:"20万"},{type:"Ukey+短信客户",singleLimit:"100万",dayLimit:"100万"}]},
	{bankcode:"CITIC",bankname:"中信银行",hotline:"95558",limitlist:[{type:"手机动态密码",singleLimit:"1000",dayLimit:"5000"},{type:"U盾",singleLimit:"100万",dayLimit:"100万"}]},
	{bankcode:"CIB",bankname:"兴业银行",hotline:"95561",limitlist:[{type:"手机动态密码版",singleLimit:"日累积范围内无限额",dayLimit:"初始5000，可至网点加大"},{type:"网银支付",singleLimit:"40万 ",dayLimit:"100万 "}]},
	{bankcode:"CEB",bankname:"光大银行",hotline:"95595",limitlist:[{type:"手机动态密码",singleLimit:"1万",dayLimit:"1万"},{type:"令牌动态密码及阳光网盾验证方式",singleLimit:"100万",dayLimit:"100万"}]},
	{bankcode:"CMBC",bankname:"民生银行",hotline:"95568",limitlist:[{type:"大众版",singleLimit:"300",dayLimit:"300"},{type:"贵宾版",singleLimit:"5000",dayLimit:"5000"},{type:"U宝用户",singleLimit:"50万",dayLimit:"50万"}]},
	{bankcode:"GDB",bankname:"广发银行",hotline:"400-830-8003",limitlist:[{type:"手机验证码",singleLimit:"3000",dayLimit:"3000"},{type:"key盾",singleLimit:"2万",dayLimit:"2万"},{type:"卡密支付",singleLimit:"1000",dayLimit:"1000"}]},
	{bankcode:"BOS",bankname:"上海银行",hotline:"95594",limitlist:[{type:"办理动态密码版个人网银（含文件证书）,开通网上支付功能",singleLimit:"6000",dayLimit:"1万"},{type:"办理E盾证书版个人网银，开通网上支付功能",singleLimit:"10万",dayLimit:"100万"}]},
	{bankcode:"SPDB",bankname:"浦发银行",hotline:"95528",limitlist:[{type:"手机动态密码",singleLimit:"500",dayLimit:"20万"},{type:"数字证书（浏览器证书或U盾）",singleLimit:"500",dayLimit:"无限额，自行设置"}]},
	{bankcode:"PAB",bankname:"平安银行",hotline:"95511",limitlist:[{type:"网银",singleLimit:"5万",dayLimit:"5万"}]},
	{bankcode:"BOB",bankname:"北京银行",hotline:"95526",limitlist:[{type:"普通版",singleLimit:"300",dayLimit:"300"},{type:"动态密码版",singleLimit:"1000",dayLimit:"5000"},{type:"证书版",singleLimit:"100万",dayLimit:"100万"}]},
	{bankcode:"HXB",bankname:"华夏银行",hotline:"95577",limitlist:[{type:"卡密码校验",singleLimit:"300",dayLimit:"1000"},{type:"手机动态验证码",singleLimit:"1000",dayLimit:"5000"},{type:"U盾",singleLimit:"5000",dayLimit:"10万"}]},
	{bankcode:"BRCB",bankname:"北京农商银行",hotline:"96198",limitlist:[{type:"大众版",singleLimit:"500",dayLimit:"500"},{type:"手机认证",singleLimit:"10万",dayLimit:"50万"},{type:"证书认证",singleLimit:"20万",dayLimit:"100万"}]},
	{bankcode:"SRCB",bankname:"上海农商银行",hotline:"021-962999",limitlist:[{type:"短信版",singleLimit:"1000",dayLimit:"5000"},{type:"证书版",singleLimit:"1万",dayLimit:"1万"}]},
	{bankcode:"CZBANK",bankname:"浙商银行",hotline:"95527",limitlist:[{type:"自助注册",singleLimit:"200",dayLimit:"200"},{type:"大众版",singleLimit:"1000",dayLimit:"1000"}]},
	{bankcode:"NBCB",bankname:"宁波银行",hotline:"95574",limitlist:[{type:"无",singleLimit:"限额由个人设置",dayLimit:"限额由个人设置"}]},
	{bankcode:"HZBANK",bankname:"杭州银行",hotline:"400-888-8508",limitlist:[{type:"卡密支付",singleLimit:"300",dayLimit:"300"},{type:"证书支付",singleLimit:"100万",dayLimit:"500万"}]}
]