import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)
console.log(process.env.BASE_URL)

export default new Router({
  mode: 'history', // history、hash
  base: '/',
  routes: [
    { path: '/', name: 'index', component: () => import('./views/home/Index.vue'), meta: { auth: false, isProduction: true } },
    { path: '/index', name: 'index', component: () => import('./views/home/Index.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/', name: 'index', component: () => import('./views/home/Index.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/404', name: 'error-404', component: () => import('./views/error/Error404.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/hegui', name: 'about-hegui', component: () => import('./views/about/Hegui.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/info', name: 'about-info', component: () => import('./views/about/InfoIntro.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/info/intro', name: 'about-info-intro', component: () => import('./views/about/InfoIntro.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/info/platform', name: 'about-info-platform', component: () => import('./views/about/InfoPlatform.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/info/org', name: 'about-info-org', component: () => import('./views/about/InfoOrg.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/info/team', name: 'about-info-team', component: () => import('./views/about/InfoTeam.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/info/partner', name: 'about-info-partner', component: () => import('./views/about/InfoPartner.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/info/contact', name: 'about-info-contact', component: () => import('./views/about/InfoContact.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/operate', name: 'about-operate', component: () => import('./views/about/OperateData.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/operate/data', name: 'about-operate-data', component: () => import('./views/about/OperateData.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/operate/report', name: 'about-operate-report', component: () => import('./views/about/OperateReport.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/notice', name: 'about-notice', component: () => import('./views/about/NoticeExamine.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/notice/examine', name: 'about-notice-examine', component: () => import('./views/about/NoticeExamine.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/notice/matter', name: 'about-notice-matter', component: () => import('./views/about/NoticeMatter.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/notice/notice', name: 'about-notice-notice', component: () => import('./views/about/NoticeNotice.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/notice/news', name: 'about-notice-news', component: () => import('./views/about/NoticeNews.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/notice/explain', name: 'about-notice-explain', component: () => import('./views/about/NoticeExplain.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/riskmanage', name: 'about-riskmanage', component: () => import('./views/about/Riskmanage.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/deposit', name: 'about-deposit', component: () => import('./views/about/Deposit.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/project', name: 'about-Project', component: () => import('./views/about/Project1.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/project1', name: 'about-Project1', component: () => import('./views/about/Project1.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/project2', name: 'about-project2', component: () => import('./views/about/Project2.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/project3', name: 'about-project3', component: () => import('./views/about/Project3.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/project4', name: 'about-project4', component: () => import('./views/about/Project4.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/project5', name: 'about-project5', component: () => import('./views/about/Project5.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/project6', name: 'about-project6', component: () => import('./views/about/Project6.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/law', name: 'about-law', component: () => import('./views/about/Law.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/article/news/:uuid', name: 'article-news', component: () => import('./views/about/NewsDetail.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/article/notice/:uuid', name: 'article-notice', component: () => import('./views/about/NewsDetail.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/article/law/:uuid', name: 'article-law', component: () => import('./views/about/NewsDetail.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/about/risktip', name: 'about-risktip', component: () => import('./views/about/Risktip.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/static/downapp', name: 'static-downapp', component: () => import('./views/static/Downapp.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/static/transfer', name: 'static-transfer', component: () => import('./views/static/Transfer.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/static/control', name: 'static-control', component: () => import('./views/static/Control.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/static/wechat', name: 'static-wechat', component: () => import('./views/static/Wechat.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/static/reg_notice', name: 'static-reg-notice', component: () => import('./views/static/RegNotice.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/static/test', name: 'static-test', component: () => import('./views/static/Test.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/help/index', name: 'help-index', component: () => import('./views/help/Index.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/help/question', name: 'help-question', component: () => import('./views/help/Question.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/event/novice', name: 'event-novice', component: () => import('./views/event/Novice.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/event/recommend', name: 'event-recommend', component: () => import('./views/event/Recommend.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/activity/may', name: 'activity-201905', component: () => import('./views/event/NineMay.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/activity/june', name: 'activity-201906', component: () => import('./views/event/NineJune.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/activity/july', name: 'activity-201907', component: () => import('./views/event/NineJuly.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/activity/august', name: 'activity-201908', component: () => import('./views/event/NineAugust.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/activity/sep', name: 'activity-sep', component: () => import('./views/event/Sep.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/product/index', name: 'product-index', component: () => import('./views/product/ProductList.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/product/vip', name: 'product-vip', component: () => import('./views/product/VipList.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/product/detail/:uuid', name: 'product-detail', component: () => import('./views/product/ProductDetail.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/plan/index', name: 'plan-index', component: () => import('./views/product/Plan.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/transfer/index', name: 'transfer-index', component: () => import('./views/product/TransferList.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/transfer/detail/:uuid', name: 'transfer-detail', component: () => import('./views/product/TransferDetail.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/shop/index', name: 'shop-index', component: () => import('./views/product/ShopList.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/account/index', name: 'member-index', component: () => import('./views/user/User.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/account/recharge', name: 'member-recharge', component: () => import('./views/user/Recharge.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/account/cash', name: 'member-cash', component: () => import('./views/user/Cash.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/invest/autobid', name: 'member-autobid', component: () => import('./views/user/Autobid.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/invest/holdlist', name: 'member-holdlist', component: () => import('./views/user/Holdlist.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/invest/backplan', name: 'member-backplan', component: () => import('./views/user/Backplan.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/deal/index', name: 'member-deal', component: () => import('./views/user/Deal.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/deal/cash', name: 'member-dealcash', component: () => import('./views/user/DealCash.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/deal/recharge', name: 'member-dealrecharge', component: () => import('./views/user/DealRecharge.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/task', name: 'member-task', component: () => import('./views/user/Task.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/voucher', name: 'member-voucher', component: () => import('./views/user/Voucher.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/recommend', name: 'member-recom-list', component: () => import('./views/user/Recommend.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/secure/security', name: 'member-security', component: () => import('./views/user/Security.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/transfer/apply/:uuid', name: 'member-transfer-apply', component: () => import('./views/user/TransferApply.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/member/depository/form', name: 'member-depository', component: () => import('./views/attestation/Deposit.vue'), meta: { auth: true, isProduction: true } },
    { path: '/spa/secure/login', name: 'secure-login', component: () => import('./views/access/Login.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/secure/register', name: 'secure-register', component: () => import('./views/access/Register.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/secure/land', name: 'secure-land', component: () => import('./views/access/Land.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/event/transfer', name: 'eventTransfer', component: () => import('./views/event/transfer.vue'), meta: { auth: false, isProduction: true } },
    { path: '/spa/user/paymentDetails', name: 'paymentDetails', component: () => import('./views/user/paymentDetails.vue'), meta: { auth: true, isProduction: true } },
  ]
})
